"use strict";
"use server";
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs';
import { cookies } from 'next/headers';

import AuthProvider from '../components/providers/AuthProvider';

export default async function RootLayout( { children }) {
  const supabase = createServerComponentClient({ cookies });

  const {
    data: { session },
  } = await supabase.auth.getSession();

  return (
    
      <html lang="en">
        <head>
          <title>{'Donna Frontend Prototype'}</title>
          <meta name="description" content={'Generated by create next app by DK Kim'} />
          <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
        </head>
        <body>
        <AuthProvider accessToken={session?.access_token}>{children}</AuthProvider>
        </body>
      </html>
    
  )
}
