import './globals.css'
import { User } from '../types/User';
export const dynamic = 'force-dynamic'
import { CalendarContextProvider } from '../context/CalendarContext';
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs'
import { cookies } from 'next/headers'


export default async function RootLayout({ children }) {
  const cookieStore = cookies()
  const supabase = createServerComponentClient({ cookies: () => cookieStore })
  const { data: session, error } = await supabase.auth.getUser()
  if (error) {
    console.error(error)
  }
  return (

    <html lang="en">
      <head>
        <title>{'Donna Frontend Prototype'}</title>
        <meta name="description" content={'Generated by create next app by DK Kim'} />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
        <link href='https://fonts.googleapis.com/css?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap' rel='stylesheet'>
        </link>
      </head>
      <body>
        <CalendarContextProvider session_user={session?.user} >
          {children}
        </CalendarContextProvider>
      </body>
    </html>

  )
}
