"use strict";
"use server";
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs';
import { cookies } from 'next/headers';
import './globals.css'

import AuthProvider from '../components/providers/AuthProvider';

export default async function RootLayout({ children }) {
  const supabase = createServerComponentClient({ cookies });

  const {
    data: { session },
  } = await supabase.auth.getSession();

  return (

    <html lang="en">
      <head>
        <title>{'Donna Frontend Prototype'}</title>
        <meta name="description" content={'Generated by create next app by DK Kim'} />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
        <link href='https://fonts.googleapis.com/css?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap' rel='stylesheet'>
        </link>
      </head>
      <body>
        <AuthProvider accessToken={session?.access_token}>{children}</AuthProvider>
      </body>
    </html>

  )
}
