import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Donna Frontend Prototype',
  description: 'Generated by create next app by DK Kim',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
      </head>

      <body className={inter.className}>{children}</body>
    </html>
  )
}
